name: learning_lidar
channels:
  - pytorch
  - defaults
  - conda-forge
  - pro
dependencies:
  - netcdf4
  - xarray
  - tensorboard
  - pip
  - pyyaml
  - torchvision
  - seaborn
  - ray-tune
  - opencv
  - astral
  - numpy
  - pandas
  - tqdm
  - openpyxl
  - matplotlib
  - pytorch
  - astropy
  - pytorch-lightning
  - jupyter
  - jupyterlab
  - scikit-learn
  - scipy
  - nb_conda
  - nc-time-axis

